version: "3"

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    command: python src/main.py
    ports:
      - "8000:8000"
    depends_on:
      - database


  database:
    image: postgres:13
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

